### ISSUE TITLE
Parallelizing Artifical Neural Networks Using CUDA C

### ISSUE THREAD

**Issue by purva98** [codezonediitj/adaboost#24]
Description of the problem : Perform parallelization of Artificial Neural Networks buy using CUDA C on the MNIST dataset. 

Me and my teammate Riddhi Thakker from Team Cutting Edge. Would like to perform this task, to get more familiar to the project,

**Comment by czgdp1807** [comment]
Well, there are many awesome libraries/frameworks to train ANNs and perform inference on pre-trained networks. The above task is not in the scope of this project. Thanks for your contributions. Closing.
