### ISSUE TITLE
CUDA libraries are installed even if they aren't built

### ISSUE THREAD

**Issue by czgdp1807** [codezonediitj/adaboost#25]
#### Description of the problem

`libbnn_cuda*` files are installed even if they aren't built. See,
https://github.com/codezonediitj/adaboost/blob/5164fea84e136cd12074c16abb8e85e853faacce/CMakeLists.txt#L46-L51

A minor check is needed to fix this,

```
if(BUILD_CUDA)
    install(...)
endif()
```

The above is just a hint not a complete solution.

**Comment by purva98** [comment]
Hello, @czgdp1807 
me and my teammate would love to work on this issue!

**Comment by czgdp1807** [comment]
Sure. Please proceed with a PR for the fix.

**Comment by Vi1i** [comment]
Hi @czgdp1807, do you have preference over generator-expressions or if statement blocks for the control?

**Comment by Vi1i** [comment]
> Hi @czgdp1807, do you have preference over generator-expressions or if statement blocks for the control?

Never mind, for the generator expression to work with OFF/ON needs a new version of cmake.
